/* Test fixture mimicking frida-server: fingerprint strings, a name-based
 * lookup against the embedded agent blob (like the "frida_agent_main"
 * dlsym), an RPC marker round-trip, and an unmodified client string.
 *
 * After tools/harden.py runs, ALL of these must still pass — because the
 * host's lookup strings and the embedded agent's symbols are rewritten
 * consistently (length-preserving) in the same file — while the kept
 * "frida:rpc" marker (used by stock Frida clients) is left untouched. */

#include <stdio.h>
#include <string.h>

/* generated byte-array embedding of the agent (like frida's GResource blob) */
extern const unsigned char embedded_agent_start[];
extern const unsigned long embedded_agent_size;
#define EMBEDDED_AGENT embedded_agent_start
#define EMBEDDED_LEN ((unsigned long)embedded_agent_size)

const char *server_banner = "frida-server";
const char *version_banner = "Frida/17.18.0";
const char *dir_name = "re.frida.server";
const char *rpc_marker = "frida:rpc";
const char *agent_path = "/frida/data/agent/modern/64/frida-agent-64.so";
const char *gum_string = "gum_init: FRIDA_GUM hello";
/* what a stock client sends over the wire — must survive hardening */
const char *client_wire = "[\"frida:rpc\",42,\"call\",\"add\",[1,2]]";

const char *frida_version_string(void)
{
    return "17.18.0";
}

static int
contains(const unsigned char *blob, unsigned long len, const char *needle)
{
    size_t n = strlen(needle);
    for (unsigned long i = 0; i + n <= len; i++) {
        if (memcmp(blob + i, needle, n) == 0)
            return 1;
    }
    return 0;
}

int
main(void)
{
    int failures = 0;

    printf("banner: %s\n", server_banner);
    printf("version: %s\n", version_banner);
    printf("dir: %s\n", dir_name);
    printf("rpc: %s\n", rpc_marker);
    printf("path: %s\n", agent_path);
    printf("mod: %s\n", gum_string);
    printf("wire: %s\n", client_wire);
    printf("agentlen: %lu\n", EMBEDDED_LEN);

    /* 1. name-based lookup of the embedded agent's entry symbol: the host's
     *    constant and the agent's symbol name must be renamed together. */
    const char *entry = "frida_agent_main";
    if (contains(EMBEDDED_AGENT, EMBEDDED_LEN, entry))
        printf("agent-entry-lookup: ok\n");
    else {
        printf("agent-entry-lookup: FAIL\n");
        failures++;
    }

    /* 2. RPC marker must round-trip: kept on both host and agent sides. */
    if (contains(EMBEDDED_AGENT, EMBEDDED_LEN, rpc_marker))
        printf("rpc-roundtrip: ok\n");
    else {
        printf("rpc-roundtrip: FAIL\n");
        failures++;
    }

    /* 3. the agent banner must match the host's own (renamed) constant. */
    if (contains(EMBEDDED_AGENT, EMBEDDED_LEN, "frida-agent (embedded)"))
        printf("banner-consistency: ok\n");
    else {
        printf("banner-consistency: FAIL\n");
        failures++;
    }

    /* 4. embedded binary data (fake PNG) must be byte-identical. */
    {
        static const char expected_png[] = {
            0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A,
            0x00, 0x00, 0x00, 0x0D, 'I', 'H', 'D', 'R',
            0x08, 0x08, 0x08, 0xDB, 0x00, 0x00, 0x00, 0x00,
            0x42, 0x00, 0x00, 0x42, 0xFF, 0x21, 0x00, 0x9E,
        };
        if (contains(EMBEDDED_AGENT, EMBEDDED_LEN, expected_png))
            printf("binary-integrity: ok\n");
        else {
            printf("binary-integrity: FAIL\n");
            failures++;
        }
    }

    printf(failures ? "RESULT: FAIL (%d)\n" : "RESULT: PASS\n", failures);
    return failures ? 1 : 0;
}
