#!/usr/bin/env bash
# Local test suite for tools/harden.py.
#
# Builds a realistic ELF fixture pair (a shared-library "agent" embedded into
# an executable "host", mirroring frida-agent inside frida-server), runs the
# hardener on it, and verifies:
#   - the hardened binary still runs and all name-based lookups pass
#   - fingerprint strings are replaced consistently (host + embedded agent)
#   - the "frida:rpc" wire marker (stock-client contract) is preserved
#   - embedded binary data is untouched
#   - the symbol table is stripped
#   - the file is renamed
# Also tests the Mach-O and PE code paths with synthetic binaries.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT
ALIAS="${HARDEN_TEST_ALIAS:-vexrd}"

fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "  ok: $*"; }

# --------------------------------------------------------------------------
echo "== building fixtures (ELF, x86_64)"
gcc -shared -fPIC -O1 -o "$BUILD/fixture-agent.so" "$HERE/fixtures/fixture-agent.c"
# embed the agent as a generated byte array (mirrors frida's GResource embedding)
python3 - "$BUILD/fixture-agent.so" > "$BUILD/embedded.c" <<'PYEOF'
import sys
data = open(sys.argv[1], "rb").read()
print("const unsigned char embedded_agent_start[] = {")
for i in range(0, len(data), 16):
    print(",".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
print("};")
print(f"const unsigned long embedded_agent_size = {len(data)};")
PYEOF
gcc -O1 -o "$BUILD/frida-server" "$HERE/fixtures/fixture-host.c" "$BUILD/embedded.c" \
    || fail "fixture build"

(cd "$BUILD" && ./frida-server > baseline.txt) || fail "baseline run"
grep -q "RESULT: PASS" "$BUILD/baseline.txt" || fail "baseline not PASS"
pass "baseline fixture runs"

# --------------------------------------------------------------------------
echo "== hardening the fixture host"
(
  cd "$BUILD"
  python3 "$ROOT/tools/harden.py" frida-server --alias "$ALIAS" --verbose \
      > harden.log 2>&1
) || { cat "$BUILD/harden.log"; fail "harden.py failed"; }
cat "$BUILD/harden.log" | sed 's/^/    /'

test -f "$BUILD/${ALIAS}-server" || fail "output not renamed to $ALIAS-server"
test ! -f "$BUILD/frida-server" || fail "old name still present"
pass "renamed to ${ALIAS}-server (process/module name no longer says frida)"

# --------------------------------------------------------------------------
echo "== verifying the hardened binary"
(cd "$BUILD" && ./${ALIAS}-server > hardened.txt) || fail "hardened binary does not run"
H="$BUILD/hardened.txt"

grep -q "RESULT: PASS" "$H" || { cat "$H"; fail "hardened fixture checks"; }
pass "hardened binary runs, all consistency checks pass (entry lookup, rpc, banner)"

grep -q "banner: ${ALIAS}-server" "$H" || fail "banner not renamed"
grep -q "version: $(echo "${ALIAS:0:1}" | tr a-z A-Z)${ALIAS:1}/17.18.0" "$H" || fail "version banner not renamed"
grep -q "dir: re.${ALIAS}.server" "$H" || fail "directory constant not renamed"
grep -q "path: /${ALIAS}/data/agent/modern/64/${ALIAS}-agent-64.so" "$H" || fail "agent path not renamed"
# "gum_init: FRIDA_GUM hello" -> "vex_init: VEXRD_VEX hello" (both frida and gum renamed)
grep -q "mod: ${ALIAS:0:3}_init: $(echo "$ALIAS" | tr a-z A-Z)_$(echo "${ALIAS:0:3}" | tr a-z A-Z) hello" "$H" || fail "gum string not renamed"
pass "fingerprint strings renamed (incl. inside the embedded agent blob)"

grep -q "rpc: frida:rpc" "$H" || fail "rpc marker (host) not kept"
grep -q 'wire: \["frida:rpc"' "$H" || fail "rpc wire format not kept"
grep -q "rpc-roundtrip: ok" "$H" || fail "rpc marker in embedded agent not kept"
pass "frida:rpc wire marker preserved (stock clients still work)"

# no leaked fingerprint strings anywhere in data sections (except the keep)
if strings "$BUILD/${ALIAS}-server" | grep -E 'frida|Frida|FRIDA|gum|Gum|GUM' | grep -v 'frida:rpc' | grep -v '^ *$'; then
  fail "fingerprint strings leaked in hardened binary"
fi
pass "no leaked frida/gum strings"

# stripped: no local symbol table
if command -v nm >/dev/null 2>&1 && nm "$BUILD/${ALIAS}-server" 2>/dev/null | grep -v '^$' | grep -qv '^ *U '; then
  # nm prints "no symbols" on stderr for stripped binaries
  out=$(nm "$BUILD/${ALIAS}-server" 2>&1 || true)
  if echo "$out" | grep -q " [tTdD] "; then fail "symbol table not stripped"; fi
fi
pass "symbol table stripped"

# embedded binary data (fake PNG) byte-identical
grep -q "binary-integrity: ok" "$H" || fail "embedded binary data was modified"
pass "embedded binary data untouched"

# --------------------------------------------------------------------------
echo "== testing Mach-O code path (synthetic)"
(
  cd "$BUILD"
  python3 "$HERE/make_synthetic.py" . >/dev/null
  python3 "$ROOT/tools/harden.py" synthetic.macho --alias "$ALIAS" --no-strip --no-rename > macho.log 2>&1
  python3 "$HERE/check_synthetic.py" "$ALIAS" synthetic.macho "macho"
) || fail "macho synthetic test"
pass "mach-o synthetic: strings replaced, rpc kept, keep-list honored"

# --------------------------------------------------------------------------
echo "== testing PE code path (synthetic)"
(
  cd "$BUILD"
  python3 "$ROOT/tools/harden.py" synthetic.exe --alias "$ALIAS" --no-strip --no-rename > pe.log 2>&1
  python3 "$HERE/check_synthetic.py" "$ALIAS" synthetic.exe "pe"
) || fail "pe synthetic test"
pass "pe synthetic: ascii + utf-16 strings replaced, rpc kept"

# --------------------------------------------------------------------------
echo
echo "ALL TESTS PASSED"
